//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.portal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category at Left.
        /// </summary>
        internal static string about_0 {
            get {
                return ResourceManager.GetString("about_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Administrative service is designed for Facilitators and Managers. Depending on your setup, this is where you can manage your learners and the content they will review. This provides a series of reports to monitor learner activities..
        /// </summary>
        internal static string about_1 {
            get {
                return ResourceManager.GetString("about_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a Facilitator or Manager to access this service. Use the Customer Id (Account) plus your Unique Id (Password), select your language then Sign In. When you are done, please remember to Sign Out when you are done to secure your data plus conserve resources..
        /// </summary>
        internal static string about_2 {
            get {
                return ResourceManager.GetString("about_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are provided for Facilitators in both English and French. If you use a Microsoft Browser (IE or Edge) and have your Language Preference set to French, the service will pick that up. Otherwise it will default to Enlish unless you specify otherwise.  Manager services are only provided in Englsh..
        /// </summary>
        internal static string about_3 {
            get {
                return ResourceManager.GetString("about_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitators do the heavy lifting for each account. They typically manage the learners and their performance. While Facilitators may have access to the content, they are not considered learners. Each Account is also setup with a Manager who can assign Facilitator status plus do a few other site routines..
        /// </summary>
        internal static string about_4 {
            get {
                return ResourceManager.GetString("about_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports come in a variety of flavours. Little online &quot;reports&quot; like this one that you are reading, is an &quot;info&quot; report and will have a blue background. Key online reports where you manage information will have a white background.  CSS and Excel reports will be generated..
        /// </summary>
        internal static string about_5 {
            get {
                return ResourceManager.GetString("about_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string access {
            get {
                return ResourceManager.GetString("access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Learner.
        /// </summary>
        internal static string addLearner {
            get {
                return ResourceManager.GetString("addLearner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string assign {
            get {
                return ResourceManager.GetString("assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Content.
        /// </summary>
        internal static string assignContent {
            get {
                return ResourceManager.GetString("assignContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned After.
        /// </summary>
        internal static string assignedAfter {
            get {
                return ResourceManager.GetString("assignedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Before.
        /// </summary>
        internal static string assignedBefore {
            get {
                return ResourceManager.GetString("assignedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available After.
        /// </summary>
        internal static string availableAfter {
            get {
                return ResourceManager.GetString("availableAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Before.
        /// </summary>
        internal static string availableBefore {
            get {
                return ResourceManager.GetString("availableBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you to assign the programs you have purchased to your learners. Select individual learners below to whom you&apos;d like to assign content or select all learners (click top left)..
        /// </summary>
        internal static string content_1 {
            get {
                return ResourceManager.GetString("content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: once content is assigned and committed, it cannot be unassigned!.
        /// </summary>
        internal static string content_10 {
            get {
                return ResourceManager.GetString("content_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then select the programs you want assigned to these learners or select all programs (click top left)..
        /// </summary>
        internal static string content_2 {
            get {
                return ResourceManager.GetString("content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then click &lt;span class=&quot;code&quot;&gt;Assign&lt;/span&gt; and the Programs will appear in the learner(s) &lt;span style=&quot;font-weight: bold; color: navy;&quot;&gt;Programs After&lt;/span&gt; field..
        /// </summary>
        internal static string content_3 {
            get {
                return ResourceManager.GetString("content_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program count will be reflected in the &lt;span style=&quot;font-weight: bold; color: navy;&quot;&gt;Assigned After&lt;/span&gt; and &lt;span style=&quot;font-weight: bold; color: navy;&quot;&gt;Available After&lt;/span&gt; fields..
        /// </summary>
        internal static string content_4 {
            get {
                return ResourceManager.GetString("content_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;span class=&quot;code&quot;&gt;Restart&lt;/span&gt; to undo what you have done, enabling you to start over.&amp;nbsp; When your assignments look good, then click &lt;span class=&quot;code&quot;&gt;Commit&lt;/span&gt;..
        /// </summary>
        internal static string content_5 {
            get {
                return ResourceManager.GetString("content_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;font-style:italic;&quot;&gt;Note: once content is assigned and committed it cannot be unassigned!&lt;/span&gt;.
        /// </summary>
        internal static string content_6 {
            get {
                return ResourceManager.GetString("content_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select the Learner(s) that will be assigned Programs.
        /// </summary>
        internal static string content_7 {
            get {
                return ResourceManager.GetString("content_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next select the Programs you wish to assign to the above Learner(s)..
        /// </summary>
        internal static string content_8 {
            get {
                return ResourceManager.GetString("content_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then Click &lt;span class=&quot;code&quot;&gt;Assign&lt;/span&gt; and the Program(s) will be moved to the Learner(s) or you can &lt;span class=&quot;code&quot;&gt;Restart.&lt;/span&gt;  When satisfied click &lt;span class=&quot;code&quot;&gt;Commit&lt;/span&gt;  but remember that once content is assigned and committed is cannot be unnassigned..
        /// </summary>
        internal static string content_9 {
            get {
                return ResourceManager.GetString("content_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those Credentials are not on file!.
        /// </summary>
        internal static string credentialError {
            get {
                return ResourceManager.GetString("credentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        internal static string custId {
            get {
                return ResourceManager.GetString("custId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Visit.
        /// </summary>
        internal static string firstVisit {
            get {
                return ResourceManager.GetString("firstVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the tiles at the top corners to begin..
        /// </summary>
        internal static string homeDirections {
            get {
                return ResourceManager.GetString("homeDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string homePageTitle {
            get {
                return ResourceManager.GetString("homePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Center.
        /// </summary>
        internal static string homeTitle {
            get {
                return ResourceManager.GetString("homeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string langFrench {
            get {
                return ResourceManager.GetString("langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visit.
        /// </summary>
        internal static string lastVisit {
            get {
                return ResourceManager.GetString("lastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Learner.
        /// </summary>
        internal static string learner {
            get {
                return ResourceManager.GetString("learner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners.
        /// </summary>
        internal static string learners {
            get {
                return ResourceManager.GetString("learners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the column headers to sort learners. Search fields for ....
        /// </summary>
        internal static string learners_1 {
            get {
                return ResourceManager.GetString("learners_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;span class=&quot;code&quot;&gt;Select&lt;/span&gt; for learner details..
        /// </summary>
        internal static string learners_2 {
            get {
                return ResourceManager.GetString("learners_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Id.
        /// </summary>
        internal static string membId {
            get {
                return ResourceManager.GetString("membId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string membPwd {
            get {
                return ResourceManager.GetString("membPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string memo {
            get {
                return ResourceManager.GetString("memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Report.
        /// </summary>
        internal static string menuActivityReport {
            get {
                return ResourceManager.GetString("menuActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Aliases.
        /// </summary>
        internal static string menuAlias {
            get {
                return ResourceManager.GetString("menuAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Report.
        /// </summary>
        internal static string menuAssessmentReport {
            get {
                return ResourceManager.GetString("menuAssessmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Content.
        /// </summary>
        internal static string menuAssignContent {
            get {
                return ResourceManager.GetString("menuAssignContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string menuChangeLanguage {
            get {
                return ResourceManager.GetString("menuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion (CSV).
        /// </summary>
        internal static string menuCompletionCSV {
            get {
                return ResourceManager.GetString("menuCompletionCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Report.
        /// </summary>
        internal static string menuCompletionReport {
            get {
                return ResourceManager.GetString("menuCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string menuDocumentation {
            get {
                return ResourceManager.GetString("menuDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitator Services.
        /// </summary>
        internal static string menuFacilitatorServices {
            get {
                return ResourceManager.GetString("menuFacilitatorServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCompletion (CSV).
        /// </summary>
        internal static string menuInCompletionCSV {
            get {
                return ResourceManager.GetString("menuInCompletionCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Leaner.
        /// </summary>
        internal static string menuLearner {
            get {
                return ResourceManager.GetString("menuLearner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners.
        /// </summary>
        internal static string menuLearners {
            get {
                return ResourceManager.GetString("menuLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners to Excel.
        /// </summary>
        internal static string menuLearnersExcel {
            get {
                return ResourceManager.GetString("menuLearnersExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string menuMyProfile {
            get {
                return ResourceManager.GetString("menuMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string menuReports {
            get {
                return ResourceManager.GetString("menuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string menuSignOut {
            get {
                return ResourceManager.GetString("menuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string new_ {
            get {
                return ResourceManager.GetString("new_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visits.
        /// </summary>
        internal static string noVisits {
            get {
                return ResourceManager.GetString("noVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string parameter {
            get {
                return ResourceManager.GetString("parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string profiles {
            get {
                return ResourceManager.GetString("profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the Profile header to sort or search for Profile ....
        /// </summary>
        internal static string profiles_1 {
            get {
                return ResourceManager.GetString("profiles_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id.
        /// </summary>
        internal static string programId {
            get {
                return ResourceManager.GetString("programId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string programs {
            get {
                return ResourceManager.GetString("programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs After.
        /// </summary>
        internal static string programsAfter {
            get {
                return ResourceManager.GetString("programsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Before.
        /// </summary>
        internal static string programsBefore {
            get {
                return ResourceManager.GetString("programsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Title.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        internal static string purchased {
            get {
                return ResourceManager.GetString("purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seach value.
        /// </summary>
        internal static string searchValue {
            get {
                return ResourceManager.GetString("searchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are internal values maintained during the Session..
        /// </summary>
        internal static string sessionVariables {
            get {
                return ResourceManager.GetString("sessionVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but a record with that identifier already exists..
        /// </summary>
        internal static string sql_2627 {
            get {
                return ResourceManager.GetString("sql_2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Id.
        /// </summary>
        internal static string uniqueId {
            get {
                return ResourceManager.GetString("uniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome..
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
