//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.portal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this Service.
        /// </summary>
        internal static string about_0 {
            get {
                return ResourceManager.GetString("about_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Category at Left.
        /// </summary>
        internal static string about_01 {
            get {
                return ResourceManager.GetString("about_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is where you can manage your learners and the content they will review. It also provides a series of reports to monitor learner activities..
        /// </summary>
        internal static string about_1 {
            get {
                return ResourceManager.GetString("about_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a Facilitator or Manager (ie NOT a learner) to access this service. Use your credentials (and select your language) then Next. When you are done, please remember to Sign Out at the top left when you are done to secure your data plus conserve resources..
        /// </summary>
        internal static string about_2 {
            get {
                return ResourceManager.GetString("about_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are provided for Facilitators in both English and French. If you use a Microsoft Browser (IE or Edge) and have your Language Preference set to French, the service will pick that up. Otherwise it will default to English unless you specify otherwise.  Manager services are only provided in Englsh..
        /// </summary>
        internal static string about_3 {
            get {
                return ResourceManager.GetString("about_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitators do the heavy lifting for each account. They typically manage the learners and their performance. While Facilitators may have access to the content, they are not considered learners. Each Account is also setup with a Manager who can add a Facilitator to the account plus do a few other site routines..
        /// </summary>
        internal static string about_4 {
            get {
                return ResourceManager.GetString("about_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports come in a variety of flavours. Little online &quot;reports&quot; like this one that you are reading, is an &quot;info&quot; report and will have a blue background. Key online reports where you manage information will have a white background.  Most key report provide CSV and/or Excel versions..
        /// </summary>
        internal static string about_5 {
            get {
                return ResourceManager.GetString("about_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account features and reports appear on the menu items at the top left. Operational features for your benefit appear on the top right. Note that this service will NOT run on small screens like a phone since large online forms etc are a key part of the deliverables..
        /// </summary>
        internal static string about_6 {
            get {
                return ResourceManager.GetString("about_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string access {
            get {
                return ResourceManager.GetString("access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string active_ {
            get {
                return ResourceManager.GetString("active?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Learner.
        /// </summary>
        internal static string addLearner {
            get {
                return ResourceManager.GetString("addLearner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email Alerts.
        /// </summary>
        internal static string alertsResend {
            get {
                return ResourceManager.GetString("alertsResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alerts will be resent on the next cycle!.
        /// </summary>
        internal static string alertsResent {
            get {
                return ResourceManager.GetString("alertsResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Programs.
        /// </summary>
        internal static string allPrograms {
            get {
                return ResourceManager.GetString("allPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string assign {
            get {
                return ResourceManager.GetString("assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        internal static string assigned {
            get {
                return ResourceManager.GetString("assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned After.
        /// </summary>
        internal static string assignedAfter {
            get {
                return ResourceManager.GetString("assignedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Before.
        /// </summary>
        internal static string assignedBefore {
            get {
                return ResourceManager.GetString("assignedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Purchased Content.
        /// </summary>
        internal static string assignPurchasedContent {
            get {
                return ResourceManager.GetString("assignPurchasedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available After.
        /// </summary>
        internal static string availableAfter {
            get {
                return ResourceManager.GetString("availableAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Before.
        /// </summary>
        internal static string availableBefore {
            get {
                return ResourceManager.GetString("availableBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string begin {
            get {
                return ResourceManager.GetString("begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Test.
        /// </summary>
        internal static string browserTest {
            get {
                return ResourceManager.GetString("browserTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed?.
        /// </summary>
        internal static string completed_ {
            get {
                return ResourceManager.GetString("completed?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you to assign the programs you have purchased to your learners. Select individual learners below to whom you&apos;d like to assign content or select all learners (click top left)..
        /// </summary>
        internal static string content_1 {
            get {
                return ResourceManager.GetString("content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: once content is assigned and committed, it cannot be unassigned!.
        /// </summary>
        internal static string content_10 {
            get {
                return ResourceManager.GetString("content_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then select the programs you want assigned to these learners or select all programs (click top left)..
        /// </summary>
        internal static string content_2 {
            get {
                return ResourceManager.GetString("content_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then click &lt;span class=&quot;code&quot;&gt;Assign&lt;/span&gt; and the Programs will appear in the learner(s) &lt;span style=&quot;font-weight: bold;&quot;&gt;Programs After&lt;/span&gt; field..
        /// </summary>
        internal static string content_3 {
            get {
                return ResourceManager.GetString("content_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program count will be reflected in the Assigned After and Available After fields..
        /// </summary>
        internal static string content_4 {
            get {
                return ResourceManager.GetString("content_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;span class=&quot;code&quot;&gt;Restart&lt;/span&gt; to undo what you have done, enabling you to start over.&amp;nbsp; When your assignments look good, then click &lt;span class=&quot;code&quot;&gt;Commit&lt;/span&gt;..
        /// </summary>
        internal static string content_5 {
            get {
                return ResourceManager.GetString("content_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;font-style:italic;&quot;&gt;Note: once content is assigned and committed it cannot be unassigned!&lt;/span&gt;.
        /// </summary>
        internal static string content_6 {
            get {
                return ResourceManager.GetString("content_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Learners are only rendered to show possible previous assignments..
        /// </summary>
        internal static string content_61 {
            get {
                return ResourceManager.GetString("content_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select the Learner(s) that will be assigned Programs.
        /// </summary>
        internal static string content_7 {
            get {
                return ResourceManager.GetString("content_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next select the Programs you wish to assign to the above Learner(s)..
        /// </summary>
        internal static string content_8 {
            get {
                return ResourceManager.GetString("content_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then click Assign and the Program(s) will be moved to the Learner(s).&lt;br /&gt;You will then have an opportunity to Commit the assignment(s) or Restart..
        /// </summary>
        internal static string content_9 {
            get {
                return ResourceManager.GetString("content_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those Credentials are not on file! Click Restart..
        /// </summary>
        internal static string credentialError {
            get {
                return ResourceManager.GetString("credentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That Password is incorrect!.
        /// </summary>
        internal static string credentialPasswordError {
            get {
                return ResourceManager.GetString("credentialPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your credentials..
        /// </summary>
        internal static string credentials {
            get {
                return ResourceManager.GetString("credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        internal static string custId {
            get {
                return ResourceManager.GetString("custId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string documentation {
            get {
                return ResourceManager.GetString("documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alert Service.
        /// </summary>
        internal static string emailAlerts_1 {
            get {
                return ResourceManager.GetString("emailAlerts_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service will email access instructions to any Learner when program(s) have been assigned by the account Facilitator. A Learner must have a valid email address in order to qualify for email alerts.&lt;br /&gt;If this service is enabled then each learner can further be configured to use the service or not; also you can resend email alerts by using Add/Edit Learners..
        /// </summary>
        internal static string emailAlerts_2 {
            get {
                return ResourceManager.GetString("emailAlerts_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status is currently.
        /// </summary>
        internal static string emailAlerts_3 {
            get {
                return ResourceManager.GetString("emailAlerts_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLED.
        /// </summary>
        internal static string emailAlerts_4 {
            get {
                return ResourceManager.GetString("emailAlerts_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        internal static string emailAlerts_5 {
            get {
                return ResourceManager.GetString("emailAlerts_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable email alerts.
        /// </summary>
        internal static string emailAlerts_6 {
            get {
                return ResourceManager.GetString("emailAlerts_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable email alerts.
        /// </summary>
        internal static string emailAlerts_7 {
            get {
                return ResourceManager.GetString("emailAlerts_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houston, we have a problem....
        /// </summary>
        internal static string errorHouston {
            get {
                return ResourceManager.GetString("errorHouston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource being accessed is not available. Restart required..
        /// </summary>
        internal static string errorPage {
            get {
                return ResourceManager.GetString("errorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Visit.
        /// </summary>
        internal static string firstVisit {
            get {
                return ResourceManager.GetString("firstVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot?.
        /// </summary>
        internal static string forgot {
            get {
                return ResourceManager.GetString("forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Credentials?.
        /// </summary>
        internal static string forgotCredentials {
            get {
                return ResourceManager.GetString("forgotCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your unique email address where we will send your credentials..
        /// </summary>
        internal static string forgot_1 {
            get {
                return ResourceManager.GetString("forgot_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0} charm below to access the content..
        /// </summary>
        internal static string labContent {
            get {
                return ResourceManager.GetString("labContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the top corner menu items to manage the system..
        /// </summary>
        internal static string labManage {
            get {
                return ResourceManager.GetString("labManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}. Welcome to the learning portal..
        /// </summary>
        internal static string labWelcome {
            get {
                return ResourceManager.GetString("labWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string langFrench {
            get {
                return ResourceManager.GetString("langFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Accessed.
        /// </summary>
        internal static string lastAccessed {
            get {
                return ResourceManager.GetString("lastAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visit.
        /// </summary>
        internal static string lastVisit {
            get {
                return ResourceManager.GetString("lastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Learner.
        /// </summary>
        internal static string learner {
            get {
                return ResourceManager.GetString("learner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner Id.
        /// </summary>
        internal static string learnerId {
            get {
                return ResourceManager.GetString("learnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners.
        /// </summary>
        internal static string learners {
            get {
                return ResourceManager.GetString("learners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner Id.
        /// </summary>
        internal static string learners_1 {
            get {
                return ResourceManager.GetString("learners_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: select/highlight either &apos;No Special Access&apos; OR any combination of the other values. Use CTRL click to select/highlight multiple values..
        /// </summary>
        internal static string learners_10 {
            get {
                return ResourceManager.GetString("learners_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Level value should NOT be changed once updated since other values depend on its state..
        /// </summary>
        internal static string learners_11 {
            get {
                return ResourceManager.GetString("learners_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Learners to Excel.
        /// </summary>
        internal static string learners_12 {
            get {
                return ResourceManager.GetString("learners_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are.
        /// </summary>
        internal static string learners_13 {
            get {
                return ResourceManager.GetString("learners_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learners available for Export..
        /// </summary>
        internal static string learners_14 {
            get {
                return ResourceManager.GetString("learners_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the column headers to sort learners, the.
        /// </summary>
        internal static string learners_1a {
            get {
                return ResourceManager.GetString("learners_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon at top to add a learner and the.
        /// </summary>
        internal static string learners_1b {
            get {
                return ResourceManager.GetString("learners_1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon at right for learner details. You can narrow this list by searching any field for any value..
        /// </summary>
        internal static string learners_1c {
            get {
                return ResourceManager.GetString("learners_1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clicking the title shows/hides this section.].
        /// </summary>
        internal static string learners_1d {
            get {
                return ResourceManager.GetString("learners_1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;span class=&quot;code&quot;&gt;Select&lt;/span&gt; for learner details..
        /// </summary>
        internal static string learners_2 {
            get {
                return ResourceManager.GetString("learners_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no Learners in this Account. Use the Add icon above to Add learners..
        /// </summary>
        internal static string learners_3 {
            get {
                return ResourceManager.GetString("learners_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this learner did not receive their &apos;Welcome&apos; email alert(s), for whatever reason, click the Email icon and the system will resend any outstanding Email Alerts..
        /// </summary>
        internal static string learners_4 {
            get {
                return ResourceManager.GetString("learners_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When done, click the icon at top to return to the Learner List..
        /// </summary>
        internal static string learners_5 {
            get {
                return ResourceManager.GetString("learners_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: &lt;b&gt;Username&lt;/b&gt; must be globally unique (suggest email). Fields up to and including Email are mandatory. The &lt;b&gt;Programs&lt;/b&gt; field is assigned elsewhere thus is read only..
        /// </summary>
        internal static string learners_6 {
            get {
                return ResourceManager.GetString("learners_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Learner.
        /// </summary>
        internal static string learners_7 {
            get {
                return ResourceManager.GetString("learners_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing mandatory field(s):.
        /// </summary>
        internal static string learners_8 {
            get {
                return ResourceManager.GetString("learners_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: clicking on the Field name (i.e. Username) will provide a description above.  Click on the description to remove it..
        /// </summary>
        internal static string learners_9 {
            get {
                return ResourceManager.GetString("learners_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Access.
        /// </summary>
        internal static string managerAccess {
            get {
                return ResourceManager.GetString("managerAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member No.
        /// </summary>
        internal static string memberNo {
            get {
                return ResourceManager.GetString("memberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string membId {
            get {
                return ResourceManager.GetString("membId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string membPwd {
            get {
                return ResourceManager.GetString("membPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string memo {
            get {
                return ResourceManager.GetString("memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Report.
        /// </summary>
        internal static string menuActivityReport {
            get {
                return ResourceManager.GetString("menuActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Aliases.
        /// </summary>
        internal static string menuAlias {
            get {
                return ResourceManager.GetString("menuAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Report.
        /// </summary>
        internal static string menuAssessmentReport {
            get {
                return ResourceManager.GetString("menuAssessmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Purchased Content.
        /// </summary>
        internal static string menuAssignPurchasedContent {
            get {
                return ResourceManager.GetString("menuAssignPurchasedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string menuChangeLanguage {
            get {
                return ResourceManager.GetString("menuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion (CSV).
        /// </summary>
        internal static string menuCompletionCSV {
            get {
                return ResourceManager.GetString("menuCompletionCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Report.
        /// </summary>
        internal static string menuCompletionReport {
            get {
                return ResourceManager.GetString("menuCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string menuDocumentation {
            get {
                return ResourceManager.GetString("menuDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alerts.
        /// </summary>
        internal static string menuEmailAlerts {
            get {
                return ResourceManager.GetString("menuEmailAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitator Services.
        /// </summary>
        internal static string menuFacilitatorServices {
            get {
                return ResourceManager.GetString("menuFacilitatorServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCompletion (CSV).
        /// </summary>
        internal static string menuInCompletionCSV {
            get {
                return ResourceManager.GetString("menuInCompletionCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Leaner.
        /// </summary>
        internal static string menuLearner {
            get {
                return ResourceManager.GetString("menuLearner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Learners.
        /// </summary>
        internal static string menuLearnersAddEdit {
            get {
                return ResourceManager.GetString("menuLearnersAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Learners.
        /// </summary>
        internal static string menuLearnersExcel {
            get {
                return ResourceManager.GetString("menuLearnersExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string menuMyProfile {
            get {
                return ResourceManager.GetString("menuMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details (Excel).
        /// </summary>
        internal static string menuProgramActivityDetails {
            get {
                return ResourceManager.GetString("menuProgramActivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string menuReports {
            get {
                return ResourceManager.GetString("menuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string menuSignOut {
            get {
                return ResourceManager.GetString("menuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string new_ {
            get {
                return ResourceManager.GetString("new_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A learner must have a name and email address to appear on this list..
        /// </summary>
        internal static string noLearners {
            get {
                return ResourceManager.GetString("noLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learner has been retrieved..
        /// </summary>
        internal static string noLearners_1 {
            get {
                return ResourceManager.GetString("noLearners_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learners have been retrieved. For a full list of learners use the Learners app that exports learners to Excel..
        /// </summary>
        internal static string noLearners_2 {
            get {
                return ResourceManager.GetString("noLearners_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learners have been retrieved based on the Search Criteria. For a full list of learners use the Learners app that exports learners to Excel..
        /// </summary>
        internal static string noLearners_200 {
            get {
                return ResourceManager.GetString("noLearners_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        internal static string noticeAssigned {
            get {
                return ResourceManager.GetString("noticeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will be assigned to a different learner profile..
        /// </summary>
        internal static string noticeN {
            get {
                return ResourceManager.GetString("noticeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You can click on the Facilitator Services tile to Add Learners and Assign Content..
        /// </summary>
        internal static string noticeNote {
            get {
                return ResourceManager.GetString("noticeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed that you have some purchases that are not assigned..
        /// </summary>
        internal static string noticeSubTitle {
            get {
                return ResourceManager.GetString("noticeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Notice.
        /// </summary>
        internal static string noticeTitle {
            get {
                return ResourceManager.GetString("noticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to take these courses myself..
        /// </summary>
        internal static string noticeY {
            get {
                return ResourceManager.GetString("noticeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Visits.
        /// </summary>
        internal static string noVisits {
            get {
                return ResourceManager.GetString("noVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        internal static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string pageAbout {
            get {
                return ResourceManager.GetString("pageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport d&apos;activité.
        /// </summary>
        internal static string pageActivityReport {
            get {
                return ResourceManager.GetString("pageActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Report.
        /// </summary>
        internal static string pageAssessmentReport {
            get {
                return ResourceManager.GetString("pageAssessmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Responses (Details).
        /// </summary>
        internal static string pageAssessmentResponses_Details_ {
            get {
                return ResourceManager.GetString("pageAssessmentResponses(Details)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Responses (Summary).
        /// </summary>
        internal static string pageAssessmentResponses_Summary_ {
            get {
                return ResourceManager.GetString("pageAssessmentResponses(Summary)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learner Assessments.
        /// </summary>
        internal static string pageAssessments {
            get {
                return ResourceManager.GetString("pageAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Readiness Test.
        /// </summary>
        internal static string pageBrowserReadinessTest {
            get {
                return ResourceManager.GetString("pageBrowserReadinessTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Report.
        /// </summary>
        internal static string pageCompletionReport {
            get {
                return ResourceManager.GetString("pageCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Activity.
        /// </summary>
        internal static string pageCustomerActivity {
            get {
                return ResourceManager.GetString("pageCustomerActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Sales Details.
        /// </summary>
        internal static string pageCustomerSalesDetails {
            get {
                return ResourceManager.GetString("pageCustomerSalesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Sales Summary.
        /// </summary>
        internal static string pageCustomerSalesSummary {
            get {
                return ResourceManager.GetString("pageCustomerSalesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string pageDefault {
            get {
                return ResourceManager.GetString("pageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string pageDocumentation {
            get {
                return ResourceManager.GetString("pageDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alerts.
        /// </summary>
        internal static string pageEmailAlerts {
            get {
                return ResourceManager.GetString("pageEmailAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCompletion Report.
        /// </summary>
        internal static string pageInCompletionReport {
            get {
                return ResourceManager.GetString("pageInCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners.
        /// </summary>
        internal static string pageLearners {
            get {
                return ResourceManager.GetString("pageLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners (Export).
        /// </summary>
        internal static string pageLearnersExcel {
            get {
                return ResourceManager.GetString("pageLearnersExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Usage.
        /// </summary>
        internal static string pageModuleUsage {
            get {
                return ResourceManager.GetString("pageModuleUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string pageProfile {
            get {
                return ResourceManager.GetString("pageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details.
        /// </summary>
        internal static string pageProgramActivityDetails {
            get {
                return ResourceManager.GetString("pageProgramActivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details (Excel).
        /// </summary>
        internal static string pageProgramActivityDetailsExcel {
            get {
                return ResourceManager.GetString("pageProgramActivityDetailsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Assigned (Excel).
        /// </summary>
        internal static string pageProgramsAssignedExcel {
            get {
                return ResourceManager.GetString("pageProgramsAssignedExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Purchased And Assigned.
        /// </summary>
        internal static string pageProgramsPurchasedAndAssigned {
            get {
                return ResourceManager.GetString("pageProgramsPurchasedAndAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string pageSessions {
            get {
                return ResourceManager.GetString("pageSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Learners.
        /// </summary>
        internal static string pageUploadLearners {
            get {
                return ResourceManager.GetString("pageUploadLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string pageWelcome1 {
            get {
                return ResourceManager.GetString("pageWelcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string parameter {
            get {
                return ResourceManager.GetString("parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string profiles {
            get {
                return ResourceManager.GetString("profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the Profile header to sort or search for Profile ....
        /// </summary>
        internal static string profiles_1 {
            get {
                return ResourceManager.GetString("profiles_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string profile_1 {
            get {
                return ResourceManager.GetString("profile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few key values from my profile..
        /// </summary>
        internal static string profile_2 {
            get {
                return ResourceManager.GetString("profile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Note: the Username for Internals is not exposed.].
        /// </summary>
        internal static string profile_3 {
            get {
                return ResourceManager.GetString("profile_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details.
        /// </summary>
        internal static string progActivity_0 {
            get {
                return ResourceManager.GetString("progActivity_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details (Excel).
        /// </summary>
        internal static string progActivity_1 {
            get {
                return ResourceManager.GetString("progActivity_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Start and End Dates and optionally a Learner Id (leave empty for all Learners) then click on the Excel Icon at the bottom right. Dates default to the previous month..
        /// </summary>
        internal static string progActivity_2 {
            get {
                return ResourceManager.GetString("progActivity_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Assigned (Excel) for.
        /// </summary>
        internal static string progAssigned_1 {
            get {
                return ResourceManager.GetString("progAssigned_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Begin button to generate the Excel which shows all the Learners that have been assigned the Program(s) selected below..
        /// </summary>
        internal static string progAssigned_2 {
            get {
                return ResourceManager.GetString("progAssigned_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id.
        /// </summary>
        internal static string programId {
            get {
                return ResourceManager.GetString("programId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string programs {
            get {
                return ResourceManager.GetString("programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs After.
        /// </summary>
        internal static string programsAfter {
            get {
                return ResourceManager.GetString("programsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Before.
        /// </summary>
        internal static string programsBefore {
            get {
                return ResourceManager.GetString("programsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Title.
        /// </summary>
        internal static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Purchased and Assigned for.
        /// </summary>
        internal static string progsPurch_1 {
            get {
                return ResourceManager.GetString("progsPurch_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on any Program Id for the Program Title..
        /// </summary>
        internal static string progsPurch_2 {
            get {
                return ResourceManager.GetString("progsPurch_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the Learners Icon to see which learners were assigned that Program Id..
        /// </summary>
        internal static string progsPurch_3 {
            get {
                return ResourceManager.GetString("progsPurch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Learners who where assigned this Program..
        /// </summary>
        internal static string progsPurch_4 {
            get {
                return ResourceManager.GetString("progsPurch_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Learners will have a line-through their learner Id..
        /// </summary>
        internal static string progsPurch_5 {
            get {
                return ResourceManager.GetString("progsPurch_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        internal static string purchased {
            get {
                return ResourceManager.GetString("purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Alerts.
        /// </summary>
        internal static string receiveAlerts {
            get {
                return ResourceManager.GetString("receiveAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Register!.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Alerts.
        /// </summary>
        internal static string resendAlerts {
            get {
                return ResourceManager.GetString("resendAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string retrieve {
            get {
                return ResourceManager.GetString("retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seach value.
        /// </summary>
        internal static string searchValue {
            get {
                return ResourceManager.GetString("searchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are internal values maintained during the Session..
        /// </summary>
        internal static string sessionVariables {
            get {
                return ResourceManager.GetString("sessionVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string setup {
            get {
                return ResourceManager.GetString("setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Portal is only available to Facilitators and/or Managers..
        /// </summary>
        internal static string signInLevel {
            get {
                return ResourceManager.GetString("signInLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We could not perform that activity..
        /// </summary>
        internal static string sql {
            get {
                return ResourceManager.GetString("sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  It seems that Username already exists..
        /// </summary>
        internal static string sqlDuplicate {
            get {
                return ResourceManager.GetString("sqlDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tileAbout {
            get {
                return ResourceManager.GetString("tileAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Report.
        /// </summary>
        internal static string tileActivityReport {
            get {
                return ResourceManager.GetString("tileActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Report.
        /// </summary>
        internal static string tileAssessmentReport {
            get {
                return ResourceManager.GetString("tileAssessmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Responses (Details).
        /// </summary>
        internal static string tileAssessmentResponsesDetails {
            get {
                return ResourceManager.GetString("tileAssessmentResponsesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Responses (Summary).
        /// </summary>
        internal static string tileAssessmentResponsesSummary {
            get {
                return ResourceManager.GetString("tileAssessmentResponsesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Content.
        /// </summary>
        internal static string tileAssignContent {
            get {
                return ResourceManager.GetString("tileAssignContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Readiness Test.
        /// </summary>
        internal static string tileBrowserReadinessTest {
            get {
                return ResourceManager.GetString("tileBrowserReadinessTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Report.
        /// </summary>
        internal static string tileCertificateReport {
            get {
                return ResourceManager.GetString("tileCertificateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Report.
        /// </summary>
        internal static string tileCompletionReport {
            get {
                return ResourceManager.GetString("tileCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string tileDocumentation {
            get {
                return ResourceManager.GetString("tileDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alerts.
        /// </summary>
        internal static string tileEmailAlerts {
            get {
                return ResourceManager.GetString("tileEmailAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilitator Services.
        /// </summary>
        internal static string tileFacilitatorServices {
            get {
                return ResourceManager.GetString("tileFacilitatorServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCompletion Report.
        /// </summary>
        internal static string tileInCompletionReport {
            get {
                return ResourceManager.GetString("tileInCompletionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners (Add/Edit).
        /// </summary>
        internal static string tileLearnersAddEdit {
            get {
                return ResourceManager.GetString("tileLearnersAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learners (Export).
        /// </summary>
        internal static string tileLearnersExport {
            get {
                return ResourceManager.GetString("tileLearnersExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Content (V5).
        /// </summary>
        internal static string tileMyContentV5 {
            get {
                return ResourceManager.GetString("tileMyContentV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Content (V8).
        /// </summary>
        internal static string tileMyContentV8 {
            get {
                return ResourceManager.GetString("tileMyContentV8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string tileMyProfile {
            get {
                return ResourceManager.GetString("tileMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Details.
        /// </summary>
        internal static string tileProgramActivityDetails {
            get {
                return ResourceManager.GetString("tileProgramActivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Activity Overall.
        /// </summary>
        internal static string tileProgramActivityOverall {
            get {
                return ResourceManager.GetString("tileProgramActivityOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Assigned.
        /// </summary>
        internal static string tileProgramsAssigned {
            get {
                return ResourceManager.GetString("tileProgramsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs Purchased and Assigned.
        /// </summary>
        internal static string tileProgramsPurchasedAndAssigned {
            get {
                return ResourceManager.GetString("tileProgramsPurchasedAndAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string tileSessions {
            get {
                return ResourceManager.GetString("tileSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string tileSignOut {
            get {
                return ResourceManager.GetString("tileSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string tileStore {
            get {
                return ResourceManager.GetString("tileStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to hide/show description.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string uniqueId {
            get {
                return ResourceManager.GetString("uniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Learners.
        /// </summary>
        internal static string uploadLearnersDownload {
            get {
                return ResourceManager.GetString("uploadLearnersDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("return", resourceCulture);
            }
        }
    }
}
